import type { Metadata } from "next";
import { Montserrat, Roboto_Slab } from "next/font/google";
import "./globals.css";

const gotham = Montserrat({
  subsets: ["latin"],
  variable: "--font-gotham",
  display: "swap",
  weight: ["400", "500", "600", "700"],
});

const robotoSlab = Roboto_Slab({
  subsets: ["latin"],
  variable: "--font-roboto-slab",
  display: "swap",
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Nexturn",
  description: "Generated by create next app",
  icons: {
    icon: [{ url: "/n.svg", type: "image/svg+xml" }],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${gotham.variable} ${robotoSlab.variable}`}>
      <body className={gotham.className}>{children}</body>
    </html>
  );
}
